service: thisdude

frameworkVersion: "<=1.26.0"

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-southeast-1
  environment:
    CLIENT_ID: '320232828836.320241223524'
    CLIENT_SECRET: ef2db9aac18fc6b29472728d6e05babf
    INSTALL_SUCCESS_URL: http://vsalfafara-site.s3-website-ap-southeast-1.amazonaws.com/#success
    INSTALL_ERROR_URL: http://vsalfafara-site.s3-website-ap-southeast-1.amazonaws.com/#error

functions:
  install: 
    handler: install.handler
    events:
      - http:
          path: install
          method: get
